name = "huggingface-daily-trending"
main = "src/index.ts"
compatibility_date = "2024-10-24"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 0 * * *"]

# 메모리 제한 및 타임아웃 설정
[limits]
cpu_ms = 50000
